m/compute_eit_data.m
m/forward_scripts/brain/lead_field_eeg_fem.m
m/forward_scripts/brain/lead_field_eit_fem.m
m/forward_scripts/brain/lead_field_meg_fem.m
m/forward_scripts/brain/lead_field_meg_grad_fem.m
m/forward_scripts/brain/lead_field_tes_fem.m
m/zef_volume_gradient.m

This was simply to reduce the chance of the function name clashing with
functions of similar names from other packages.

Renamed m/{volume_gradient → zef_volume_gradient}.m

---

m/compute_eit_data.m
m/forward_scripts/brain/lead_field_eeg_fem.m
m/forward_scripts/brain/lead_field_eit_fem.m
m/forward_scripts/brain/lead_field_meg_fem.m
m/forward_scripts/brain/lead_field_meg_grad_fem.m
m/forward_scripts/brain/lead_field_tes_fem.m
m/forward_scripts/gravity/compute_gravity_data.m
m/forward_scripts/gravity/lead_field_gravity.m
m/forward_scripts/gravity/lead_field_gravity_grad.m
m/zef_mesh_refinement.m
m/zef_refinement_step.m
m/zef_tetra_volume.m

Again, just like with commit c25289c59d555367a91bbec5827b707761e3efb3, the
purpose of this commit is to reduce the chance of the tetrahedron volume
function clashing with external ones.
Also again, file formats were changed from dos → unix, so a few files will
look like they've been replaced entirely, but in reality only the function
invocation as altered to match the new name.

Renamed m/{volume → zef_tetra_volume}.m

---

m/zef_tetra_volume.m

Now the volume absolute values should no longer be printed on screen.

Added a missing semicolon to tetra volume calculation

---

m/zef_cem_electrode.m

Also added a few line breaks, commas and line continuations `...` inside the
non-empty branch of the input array check, in the generation of the output
variable `s_points`, to make the code more readable. Commas with line
continuations generate a row vector the same way that white space does.

zef_cem_electrode: added a check for empty input array

---

data/scripts_for_importing/import_scripts_legacy/fs2zef.sh

All parameters (subjects directory, individual subject folder in the subjects
directory and FreeSurfer (FS) output directory) are read as inputs to the
script. This means that the script has to be called as
fs2zef.sh <subjects dir> <individual subject dir> <FS output dit>
The existence of the required directories are checked and if they do not
exist, the script does nothing but prints an error message to the screen.

fs2zef: initial parametrization and fixing of input and output paths

---

m/zef_import_segmentation_legacy.m
m/zef_load.m
m/zef_remove_system_fields.m
m/zeffiro_interface_segmentation_tool.m
zeffiro_interface.m

This consists of the following 5 changes.
1. zef_import_segmentation_legacy: empty compartment cells deactivated
Added a conditional statement that deactivates the selection of empty
brain compartments.
2. zef_load: only deactivate display, if nodisplay is set in startup options
3. zef_remove_system_fields: added start_mode to system fields
Now start_mode is properly reset during startup.
4. zeffiro_interface_segmentation_tool: removed calls to zef_update
This prevents the unintended activation of checkboxes related to loaded
but empty brain compartments.
5. zeffiro_interface: added calls to zef_build_compartment_table
Now the segmentation tool compartment GUI should be built properly.

Segmentation tool: fix (un)setting of empty compartment tickboxes during startup

---

m/forward_scripts/brain/lead_field_eeg_fem.m
m/forward_scripts/brain/lead_field_matrix.m
m/forward_scripts/brain/zef_lead_field_sign.m

Also, the sign check was moved to the end of `lead_field_matrix` from
`lead_field_eeg_fem`, because the source interpolation after at the end of
`lead_field_matrix` caused yet another sign flip.
The individual commit messages of this squashed set of commits can be found
below. Don't forget to see the attached diff as well before accepting the pull
request.
-----------------------------
- Updated function `zef_lead_field_sign` to calculate the signs of the lead
field in x-, y- and z-directions separately.
- The function `lead_field_eeg_fem` multiplies the columns of `L_eeg`
corresponding to these directions to ensure correct `L_eeg` orientation.
Moved EEG lead field sign flip(s) to the end of lead_field_matrix from lead_field_eeg_fem
zef_lead_field_sign: ensure the test electrodes are in …

Check sign of lead field in x-, y- and z-directions separately

---

m/zef_get_profile_parameters.m
m/zef_open_parameter_profile.m
profile/multicompartment_head/zeffiro_parameters.ini

The point is to prevent ZI from unintentionally overwriting the parameters one
wishes to display in the Figure tool, which it does with the parameter
profiles Segmentation and Sensors, when displayed parameters are set in Mesh
Visualization Tool.

Added a free-form parameter

---

m/lead_field/zef_ew_dipoles.m
m/lead_field/zef_fi_dipoles.m
m/operators/zef_stiffness_matrix.m
m/zef_adjacency_matrix.m
m/zef_build_electrodes.m
m/zef_hdiv_interpolation.m
m/zef_transfer_matrix.m
m/zef_waitbar.m
m/zef_whitney_interpolation.m

The waitbar should now work again (and not cause Zeffiro to crash because of a type error), and at least the EEG routine seems to work as before. Individual commit messages from the squashed branch are listed below.
Started fixing waitbar
Still need to remove the unnecessary close(wb) calls that were added into the lead field routine by someone...
Added cleanup objects for waitbars and removed unnecessary close(wb) from lead field files
Progress bar almost works?
Now all that needs figuring out is why h_text gets added to the waitbar axis h_axes children multiple times.
NOW zef_waitbar works?
Duplicated graphical elements are no longer initialized and the waitbar text is updated accordingly.

Squashed branch fix_waitbar_1 into a single commit

---

m/zef_waitbar.m

So I noticed yesterday that the function `zef_waitbar > init_figure`does not accept negative coordinates, like it should. This is fixed now, along with the indentation and white space issues introduced since I last saw the file.
See the attached commit the see what was changed.

131 allow negative coordinates as arguments to zef waitbar init figure

---

scripts/zef_meshing_example.m

Also call `zef_save` to save the resulting project file. Closes #149.

zef_meshing_example: added the missing project_struct initialization

---

.gitignore
.gitmodules
external/README.md
zeffiro_setup.m

This simplifies the installation process somewhat, and also makes the lives of Git users easier. Now the (free) dependencies can be installed with a simple
git submodule update --init --recursive
or in conjunction with downloading Zeffiro Interface with
git clone --recurse-submodules https://github.com/sampsapursiainen/zeffiro_interface.git
or
git clone --recursive https://github.com/sampsapursiainen/zeffiro_interface.git
and then running
zeffiro_setup
in the Matlab console to run the installation scripts of the dependencies in a single batch.
This is a squashed commit that closes #156. Individual commit messages can be seen below.
------------------------------------------------------
.gitignore: allowed the file .gitmodules
Removed external/CVX folder from index
Added external/CVX as a …

Add external libraries as git submodules

---

scripts/specialized/inverse_sensitivity/inverse_sensitivity_fn.m
scripts/specialized/inverse_sensitivity/zef_rec_diff.m
scripts/specialized/inverse_sensitivity/zef_rec_min_diff.m
scripts/specialized/inverse_sensitivity/zef_sensitivity_map_dipoleScan.m
scripts/specialized/inverse_sensitivity/zef_sensitivity_map_mne.m

What the title says. [Argument validation][argval] was also added. This is a squashed compilation of multiple commits. Individual commit messages can be seen below.
[argval]: https://se.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html
-----------------------------------------------------------
Started cleaning up the functions that will be used to test for the sensitivity of inversion in the realistic head model case
Rename mne_sensitivity_fn to inverse_sensitivity_fn
Also allow passing in Dipole Scan as a possible inverse method
zef_sensitivity_map_dipoleScan: pass a function pointer to max diff function instead of a name of the function
inverse_sensitivity_fn: add input flag use_gpu
zef_sensitivity_map_dipoleScan: added argument validation functions …

Change sensitivity scripts to a more batch job -friendly form, as in into functions

---

scripts/specialized/inverse_sensitivity/inverse_sensitivity_fn.m

What the title says. Also turned some existing arguments into name–value pairs, to highlight the optionality of the mesh and lead field constructions.

inverse_sensitivity_fn: allow passing in more lead field parameters as name–value arguments

---

scripts/studies/inverse_sensitivity/inverse_sensitivity_fn.m

Turns out it might be useful the also get the lead field from Puhti. These commits add `L` as a second output argument, but also add a new input name–value argument for adjusting the lead field filter quantile.

Return lead field from inverse sensitivity fn

---

m/zef_import_segmentation.m

By adding the option 'sensor_taglist_filename' to the sensor line in a segmentation import script, one can set the filename from which Zeffiro will read the textual labels of the sensors.
Remove an extra quotation mark
This worked on Shannon, at least.

zef_import_segmentation: added sensor tag label import support

---

scripts/scripts_for_importing/reconstruction_from_edf_fn.m

This function reads an EDF or European Data Format file into a matrix that can be fed into `zef.reconstruction`. The rows contain time series data for each of the electrode columns in the file.

Add reconstruction_from_edf_fn

---

+tests/LeadFieldTest.m
+tests/README.md

Tests can be added here, once we have time. See [Matlab's class-based testing documentation][cbt] on how to add tests. Most notably, any test class file names need to end in the string `Test`.
[cbt]: https://se.mathworks.com/help/matlab/matlab_prog/author-class-based-unit-tests-in-matlab.html

Add beginnings of Zeffiro Interface test package

---

.editorconfig
.gitignore

This file instructs editors that know about it to follow the instructions specified within. For example, newlines might be restricted to simple line feeds `lf` instead of carriage returns + line feeds `crlf`, which generate visual noise in Git diffs, as Git is whitespace aware in its default configuration.

Allow and add .editorconfig file

---

m/zef_waitbar.m

- This takes care of any integer values being passed in as input.
- In the future, the function should probably be updated to use the new datetime function in displaying dates, instead of the deprecated datestr.
- Closes #229.

zef_waitbar: convert first argument to double

---

+utilities/figure_without_colorbar_fn.m
+utilities/figures_from_folder_without_colorbars_fn.m

- The functions are `figure_without_colorbar_fn` and `figures_from_folder_without_colorbars_fn`.
- The first one handles a single figure, and the second handles all figures in a given folder. The figures are opened, their colorbar visibilities are set to false and then the figures are saved and closed.

utilities: add functions which save figures without colorbars

---

m/zef_start_config.m
zeffiro_interface.m

This is a squashed set of commits. See the individual commit messages below for what was changed. Closes #235.
-----------------------------------------------------------
zeffiro_interface: change position of zef.start_mode initialization
- The field is now initialized before zef_start_config is called, so that it might be used within it.
- Also ran the MATLAB Smart Indentation tool on the file.
zef_start_config: add error handling to evalc calls
- Now warnings are issued, if the external optimization plugins are not found after their addition to Matlab path has been attempted.
- If Zeffiro was started with a GUI, this warning is given as a blocking error modal window. If the Zeffiro GUI was not initialized, this is a simple non-blocking warning.
zef_start_config: add a warning message …

Add error handling to zef_start_config

---

.gitattributes

- Now `CRLF` should be normalized to `LF`, when text files are committed on Windows machines.
- The user can of course control this, if they set `core.autocrlf` or `core.eol` Git settings on their local machine.
- Closes #240.

.gitattributes: remove eol=lf from text file settings
